language: python
sudo: required
group: deprecated-2017Q4
services:
- docker
before_install:
- git submodule update --init --recursive
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker run --rm --privileged multiarch/qemu-user-static:register
- cp ./Dockerfile appdaemon/Dockerfile
install:
- docker build --rm --no-cache -t stevebargelt/appdaemon-rpi appdaemon/
- docker push stevebargelt/appdaemon-rpi
script: true
notifications:
  slack:
    rooms:
      secure: NAGY4j0sY9mKm+eY0M1T//JoL5zCJc/xx8dYSRii4hkCxIVnn4Or7vmov9NGzZNmgeYKIcSPtPDbwCqIG+cUvIHnnlRtaFrBWJo4WYv4jAFMi5Z8ZHwfgsogwwM4KJbHlxiL9a/bRE6uBWVHOfrnL49yGBNu1q/XTlyiVtD1zryxVJAGPg1xdQm3yKGXADe5Laox/mrSF8ZrEKUPwQP1fGiBOxJ4mF52ed927/mlh98ltLRFdCKu1LBXMCZdlvwrdiwaKDrV6SRRCvAO96p2ZbEhF77WGp8FAW4iLrwHsiKYmOfWkoz1/oxytPfT3tENUrQ/g6ZVh++Ot/AQ2gj7aH1furFKKhuNucBxnYbix0X3Fl1qXTqHI3K78Gy9ijGifMOjmjrhLaB859cy+Nm4XQU9iylKmRENFT6QiFOjy+mkUAnacklEC1htB6eMKdH48R4m6rcCXtF8qnNLWSekizqfkRa4Z/FJrHdTah2yGcReBy64CPrJpSV26UpToAC6MY9p0lXnd8avg/TINsw30jBCDbhK0JqZqyCIKZqRd8dGowsHXxOqBEpjAUB8JjcVcQRysRPNcID15Dj/zNNggq7KxOoQa9NFtVVw3coH7A3PJbvClfXIOybfzcVChvAn2HkO/vnDrly4zhg9jZtUjR/dm7croSvPnPBzz7rrxXo=
    template:
    - Status=%{result}, Job=%{repository_name}, Build=%{build_number}, URL=%{build_url},
      HUB=https://hub.docker.com/r/stevebargelt/appdaemon-rpi/
    on_success: change
    on_failure: always